### ISSUE TITLE
[Feature] ZRR-42: Report API 개발

### ISSUE THREAD

**Issue by doojoo9999** [TeamBDMJ/Zziririt#18]
## Description
- 설명: Report API 개발
- 참조 해야하는 지라 티켓 : ZRR-42

## Todo
- [x] ERD 작성
![image](https://github.com/TeamBDMJ/Zziririt/assets/96476393/a249bcca-4c0b-4862-abd5-1cfd9d0c2982)

- [x] userReport // 유저 신고 기능. 신고할 때 마다 report 수치가 1씩 증가해야 함
- [x] 관리자가 userId를 입력하여 member_status를 normal <-> banned 변경할 수 있음
- [x] banUser // 유저 정지 기능. 관리자는 회원을 n일간 정지시킬 수 있음 (최대 10000일)
- [x] report // 유저로 부터 발송된 report를 관리함. (신고한 사람, 신고 당한 사람, 신고 게시글, 신고 댓글과 신고 사유)

## ETC
- 고려해야할 점..
