### ISSUE TITLE
[Test] ZRR-53: Post Entity Test Code 작성 및 메서드 버그 수정

### ISSUE THREAD

**Issue by Moveuk** [TeamBDMJ/Zziririt#27]
## Description
- 설명: Post Entity Test Code 작성 및 메서드 버그 수정
- 참조 해야하는 지라 티켓 : ZRR-53

## Todo
- [x] 알맞은 테스트 코드 Spec 선정
- [x] Post Entity Test Code 작성
- [x] Test Code로 인한 버그 발견 후 수정

## ETC
- 고려해야할 점..
