### ISSUE TITLE
[Feature] ZRR-60: 회원 등급 조정 기능

### ISSUE THREAD

**Issue by doojoo9999** [TeamBDMJ/Zziririt#32]
## Description
- 설명: 회원 등급 조정 API 개발
- 참조 해야하는 지라 티켓 : ZRR-60

## Todo
- [x] Admin은 Member의 회원 등급을 조정할 수 있다. (ADMIN, STREAMER, BOARD_MANAGER, VIEWER)
- [x] Streamer은 BOARD_MANAGER를 임명할 수 있다.
- [x] Streamer은 BOARD_MANAGER를 해임할 수 있다.
- [x] Admin은 Streamer가 갖는 권한을 모두 포함하고 있다.
