### ISSUE TITLE
[Chore] ZRR-66: 프로젝트 CI 수정 및 CD 구성

### ISSUE THREAD

**Issue by Moveuk** [TeamBDMJ/Zziririt#51]
## Description
- 설명: 프로젝트 CI/CD 구성: github actions + AWS EC2 + Docker
- 참조 해야하는 지라 티켓 : ZRR-66

## Todo
- [x] github actions workflows yml 작성
- [x] aws ec2 세팅
- [x] docker zziririt으로 업로드

## ETC
- 고려해야할 점..
