### ISSUE TITLE
[Chore] ZRR-73: application.yml 및 env파일 최적화, build.gradle version hard code 수정 AppRunner log 추가

### ISSUE THREAD

**Issue by Moveuk** [TeamBDMJ/Zziririt#55]
## Description
- 설명: application.yml 및 env파일 최적화, build.gradle version hard code 수정, AppRunner log 추가
- 참조 해야하는 지라 티켓 : ZRR-

## Todo
- [x] application.yml 및 env파일 최적화
- [x] build.gradle version hard code 수정
- [x] AppRunner log 추가

## ETC
- 고려해야할 점..
