### ISSUE TITLE
[Feature] ZRR-71: Board 조회 api 및 정책 적용

### ISSUE THREAD

**Issue by miso1105** [TeamBDMJ/Zziririt#60]
## Description
- 설명: 게시판 조회, 스트리머 게시판 신청 및 수정 API 작성, 스케줄러 적용
- 참조 해야하는 지라 티켓 : ZRR-71

## Todo
- [x] ERD 작성
- [x] 부모게시판, 자식 게시판 조회 API
- [x] 스트리머 게시판 신청 폼에 이미지 업로드 기능 적용하기
- [x] 신청 url, 신청 게시판 이름, 사진 url DB에 저장하기
- [x] 스트리머 게시판 활동 기간 확인 후 스케줄러 적용하기 

## ETC
- 고려해야할 점..
