### ISSUE TITLE
[Refactor] ZRR-86: Board 리팩토링

### ISSUE THREAD

**Issue by miso1105** [TeamBDMJ/Zziririt#79]
## Description
- 설명: Board 리팩토링
- 참조 해야하는 지라 티켓 : ZRR-86

## Todo
- [x] 엔티티클래스 추가: url, 스트리머 게시판인지 + 찌리릿의 게시판인지 알 수 있는 enum
- [x] 스트리머 게시판 조회: 스트리머게시판 전체조회 + 페이징 없이 자체의 보드아이디, 보드url , 스트리머 닉네임 지정 조회
- [x] 자식 게시판 조회: [보드 아이디, 보드 네임] 리스트로 반환.

## ETC
- 고려해야할 점..
